server {
    listen 8080;
    client_max_body_size 25m;

    location = /local-health {
        access_log off;
        return 204;
    }

    location / {
        proxy_pass http://191.252.181.168;
        proxy_set_header Host 191.252.181.168;
        proxy_connect_timeout 15s;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
