package com.marketinghub.facebookads;

/**
 * Motivos que disparam uma solicitação automática de pausa para uma campanha Facebook.
 */
public enum FacebookCampaignStopReason {
    ADMIN_EXPERIMENT_PAUSED,
    FIRST_FORM_SUBMISSION_STANDBY,
    FORM_ZERO_CONVERSION_RULE_OF_THREE,
    LOW_TICKET_ZERO_PURCHASE_STATISTICAL_FINANCIAL,
    LOW_TICKET_TRAFFIC_COST_ECONOMICALLY_UNVIABLE,
    LOW_IMPRESSIONS_AFTER_RUNNING_TIME,
    TARGET_AUDIENCE_LOW_INTEREST_STATISTICAL,
    LOW_FORM_ENTRY_NO_SUBMISSION_AFTER_SPEND
}
