stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}-m2
  paths:
    - .m2/repository
  policy: pull-push

build:
  stage: build
  image: maven:3.9.8-eclipse-temurin-21
  script:
    - mvn -B verify
    - mvn -B package -DskipTests
  artifacts:
    paths:
      - backend/ads-service/target/*.jar
    expire_in: 1 week

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --no-cache openssh rsync
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    - chmod 600 id_rsa
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts
  script:
    - mv backend/ads-service/target/*.jar backend/ads-service/target/app.jar
    - rsync -az --delete -e "ssh -i id_rsa -o StrictHostKeyChecking=no" backend/ads-service/target/app.jar lookgen@$VPS_HOST:/opt/lookgen/app/
    - ssh -i id_rsa lookgen@$VPS_HOST "sudo -n /usr/bin/systemctl restart lookgen-backend.service"
