version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=marketing
      - POSTGRES_PASSWORD=marketing
      - POSTGRES_DB=marketing
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
