import test from 'node:test';import assert from 'node:assert/strict';
import {buildRequest,boundary,parseResult} from '../src/vega/v1/pipeline/adjustment/processor.mjs';
import {runOnce} from '../src/worker.mjs';import {mkdtemp,rm,readdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
const job={id:1,status:'RUNNING',context:{input:{occasion:'Almoço informal',existingSelection:'Camisa branca'},inheritedLearning:{limit:'Amostra pequena'}}};
const card={cardId:'1',action:'Acomode o caimento da camisa.',application:'Alinhe o tecido sem apertar.',occasion:'Almoço informal',selfAssessmentPrompt:'Ficou confortável?',usesOnlyAvailableItems:true};
const raw=c=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(c)}]}],usage:{input_tokens:100,output_tokens:50}});
test('request usa Flex, schema versionado e contexto segregado',async()=>{const request=await buildRequest(job,'gpt-5-mini');assert.equal(request.service_tier,'flex');assert.equal(request.text.format.strict,true);assert.equal(request.store,false);assert.match(request.input[0].content,/Amostra pequena/);assert.ok(request.text.format.schema.required.includes('application'));});
test('limite exclui aquisição sem tratar limite como resultado pronto',()=>{assert.ok(boundary({input:{optionalNote:'quero comprar outra roupa'}}));assert.equal(boundary(job.context),null);});
test('resposta completa e contextual preserva o identificador',()=>assert.deepEqual(parseResult(raw(card),job),card));
test('respostas ausentes, truncadas, alheias e de compra falham fechadas',()=>{for(const c of [null,{...card,application:''},{...card,cardId:'2'},{...card,occasion:'Outra ocasião'},{...card,action:'Compre outra camisa'},{...card,usesOnlyAvailableItems:false}])assert.throws(()=>parseResult(raw(c),job));assert.throws(()=>parseResult({status:'incomplete'},job));});
test('outbox recupera callback sem nova inferência e preserva response',async()=>{
 const outbox=await mkdtemp(join(tmpdir(),'vega-outbox-'));const previousFetch=globalThis.fetch;let modelCalls=0,callbacks=0,queued=true,fail=true;
 globalThis.fetch=async(url,options={})=>{if(url==='https://model.local/responses'){modelCalls++;return new Response(JSON.stringify(raw(card)));}if(url.endsWith('/pending'))return new Response(JSON.stringify(queued?[job]:[]));if(url.endsWith('/claim')){queued=false;return new Response(JSON.stringify(job));}if(url.endsWith('/request'))return new Response('');if(url.endsWith('/result')){callbacks++;if(fail)return new Response('',{status:503});assert.deepEqual(JSON.parse(options.body).rawResponse,raw(card));return new Response('{}');}throw new Error(url);};
 try{const config={backend:'http://backend.local',token:'synthetic',key:'synthetic',model:'gpt-5-mini',openaiUrl:'https://model.local/responses',outbox};await assert.rejects(runOnce(config),/503/);assert.equal(modelCalls,1);assert.equal((await readdir(outbox)).length,1);fail=false;await runOnce(config);assert.equal(modelCalls,1);assert.equal(callbacks,2);assert.deepEqual(await readdir(outbox),[]);}finally{globalThis.fetch=previousFetch;await rm(outbox,{recursive:true,force:true});}
});
