CREATE TABLE prompt_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    source_filename VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE prompt_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_list_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    prompt TEXT NOT NULL,
    CONSTRAINT fk_prompt_list_items_list FOREIGN KEY (prompt_list_id) REFERENCES prompt_lists(id) ON DELETE CASCADE
);

CREATE INDEX idx_prompt_list_items_list ON prompt_list_items(prompt_list_id);
