spring.application.name=facebook-ads-worker
backend.base-url=http://191.252.92.222:8000
instagramcampaign.scheduler.delay=60000
backend.api-prefix=/api
facebook.ad-set.daily-budget=2000
facebook.ad-set.billing-event=IMPRESSIONS
facebook.ad-set.optimization-goal=LINK_CLICKS
facebook.ad-set.destination-type=WEBSITE
facebook.ad-set.target-country=BR
facebook.page-id=
facebook.instagram-actor-id=
facebook.website-url=https://example.com
facebook.creative.message-template=%s
facebook.creative.call-to-action-type=LEARN_MORE

