package com.marketinghub.nichocnae.sourcesearcher;

import java.time.Instant;

/** Representa uma fonte candidata persistida pelo backend com escore e risco após conclusão da etapa três. */
public record SourceCandidateResponse(
        Long sourceCandidateId,
        Long researchCycleId,
        Long researchQueryId,
        String sourceUrl,
        String sourceTitle,
        String sourceSnippet,
        String sourceDomain,
        String sourceGroup,
        String searchProvider,
        Integer searchPosition,
        String status,
        Integer relevanceScore,
        String rejectionReason,
        String sourceIntent,
        Integer routineEvidenceScore,
        Boolean commercialPageRisk,
        Boolean solutionLanguageRisk,
        String sourceClassificationType,
        Integer sourceFreshnessScore,
        Boolean outdatedSourceRisk,
        Integer brazilRelevanceScore,
        Integer autonomousProfessionalEvidenceScore,
        Boolean structuredBusinessDriftRisk,
        Instant publishedAt,
        Instant createdAt,
        Instant updatedAt) {
    /** Mantém compatibilidade para respostas antigas sem indicadores de atualidade e aderência MEI/autônomo. */
    public SourceCandidateResponse(
            Long sourceCandidateId,
            Long researchCycleId,
            Long researchQueryId,
            String sourceUrl,
            String sourceTitle,
            String sourceSnippet,
            String sourceDomain,
            String sourceGroup,
            String searchProvider,
            Integer searchPosition,
            String status,
            Integer relevanceScore,
            String rejectionReason,
            String sourceIntent,
            Integer routineEvidenceScore,
            Boolean commercialPageRisk,
            Boolean solutionLanguageRisk,
            Instant createdAt,
            Instant updatedAt) {
        this(
                sourceCandidateId,
                researchCycleId,
                researchQueryId,
                sourceUrl,
                sourceTitle,
                sourceSnippet,
                sourceDomain,
                sourceGroup,
                searchProvider,
                searchPosition,
                status,
                relevanceScore,
                rejectionReason,
                sourceIntent,
                routineEvidenceScore,
                commercialPageRisk,
                solutionLanguageRisk,
                null,
                null,
                false,
                null,
                null,
                false,
                null,
                createdAt,
                updatedAt);
    }
}
