CREATE TABLE sales_video_provider_model (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(80) NOT NULL,
    display_name VARCHAR(140) NOT NULL,
    manufacturer_name VARCHAR(120) NOT NULL,
    aggregator_name VARCHAR(120) NOT NULL,
    provider_account_key VARCHAR(80) NULL,
    route_key VARCHAR(120) NOT NULL,
    provider_name VARCHAR(80) NOT NULL,
    provider_family VARCHAR(40) NOT NULL,
    adapter_key VARCHAR(80) NOT NULL,
    external_model_id VARCHAR(120) NOT NULL,
    recommended_use VARCHAR(500) NOT NULL,
    lifecycle_status VARCHAR(24) NOT NULL,
    clip_duration_seconds INT NOT NULL,
    max_direct_duration_seconds INT NOT NULL,
    supports_hero_video TINYINT(1) NOT NULL DEFAULT 0,
    supports_scene_assembly TINYINT(1) NOT NULL DEFAULT 0,
    requires_source_image TINYINT(1) NOT NULL DEFAULT 0,
    credits_url VARCHAR(500) NULL,
    documentation_url VARCHAR(500) NOT NULL,
    adapter_verified TINYINT(1) NOT NULL DEFAULT 0,
    pricing_verified TINYINT(1) NOT NULL DEFAULT 0,
    pricing_amount_usd DECIMAL(12,6) NULL,
    pricing_unit VARCHAR(24) NULL,
    pricing_quantity DECIMAL(12,4) NULL,
    pricing_resolution VARCHAR(40) NULL,
    pricing_includes_audio TINYINT(1) NULL,
    pricing_source_url VARCHAR(500) NULL,
    pricing_observed_at DATETIME NULL,
    pricing_research_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    pricing_research_notes VARCHAR(1000) NULL,
    pricing_research_raw_response LONGTEXT NULL,
    pricing_research_model VARCHAR(120) NULL,
    commercial_license_verified TINYINT(1) NOT NULL DEFAULT 0,
    quality_gate_verified TINYINT(1) NOT NULL DEFAULT 0,
    notes VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sales_video_provider_model_code (code),
    UNIQUE KEY uk_sales_video_provider_model_provider (provider_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
