package com.marketinghub.facebookads.playbook;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;

/**
 * Targeting specs generated by the workflow (one per slot).
 */
@Entity
@Table(name = "experiment_adset_spec")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExperimentAdSetSpec {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "workflow_id", nullable = false)
    @ToString.Exclude
    private ExperimentAdSetWorkflow workflow;

    @Enumerated(EnumType.STRING)
    @Column(length = 32, nullable = false)
    private ExperimentAdSetSpecSlot slot;

    @Column(length = 255)
    private String label;

    @Column(name = "age_min")
    private Integer ageMin;

    @Column(name = "age_max")
    private Integer ageMax;

    @Column(name = "targeting_spec", columnDefinition = "LONGTEXT")
    private String targetingSpec;

    @Column(name = "validation_status", length = 32)
    private String validationStatus;

    @Column(name = "validation_response", columnDefinition = "LONGTEXT")
    private String validationResponse;

    @Column(name = "reach_status", length = 32)
    private String reachStatus;

    @Column(name = "reach_response", columnDefinition = "LONGTEXT")
    private String reachResponse;

    @Column(name = "reach_lower_bound")
    private Long reachLowerBound;

    @Column(name = "reach_upper_bound")
    private Long reachUpperBound;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;
}
