package com.marketinghub.salesvideo.dto;

import com.marketinghub.salesvideo.VideoProjectStatus;
import java.time.Instant;

/** Representa a definição editável de um vídeo no estúdio administrativo. */
public record VideoProjectDto(
    Long id,
    String tenantId,
    Long productId,
    Long experimentId,
    Long salesVideoProfileId,
    String campaignKey,
    String videoCategory,
    String contextType,
    String productionMode,
    String targetChannel,
    String format,
    String title,
    String objective,
    String storyText,
    String funnelStage,
    String primaryMetric,
    String hookText,
    String scriptText,
    String scenePlan,
    String visualReferences,
    String characterBible,
    String environmentBible,
    String objectBible,
    String visualStyleGuide,
    String imageGenerationPlan,
    String continuityRules,
    String voiceoverPlan,
    String soundtrackPlan,
    String captionPlan,
    String ctaText,
    Integer targetDurationSeconds,
    String providerPlan,
    String editingNotes,
    String qualityGate,
    VideoProjectStatus status,
    String createdBy,
    String updatedBy,
    Instant createdAt,
    Instant updatedAt) {}
