spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marketinghub
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
