package com.marketinghub.oprm.nichocnae.routinequalitygate.service.pending;

import java.time.Instant;

/** Representa um cartão de rotina pendente de avaliação pela etapa sete do OPRM NichoCNAE. */
public record RecordRoutineQualityGatePending(
    Long routineCardId,
    Long researchCycleId,
    String nicheName,
    String routineSummary,
    String painsSummary,
    String resultsSummary,
    String mechanismOpportunitiesSummary,
    String customerBehaviorSummary,
    String channelsSummary,
    String evidenceSummary,
    String sourceDomains,
    Integer cardConfidenceScore,
    Integer sourceCount,
    Integer signalCount,
    Integer questionSignalCount,
    Integer painSignalCount,
    Integer operationalDifficultyCount,
    Integer mechanismOpportunityCount,
    Integer routineTaskCount,
    Integer commercialObjectCount,
    Integer languageMarkerCount,
    Integer solutionLanguageRiskCount,
    Integer routineEvidenceScore,
    Integer difficultyEvidenceScore,
    Integer sourceDiversityScore,
    Integer solutionLanguageRiskScore,
    Integer brazilianSourceCount,
    Integer recentSourceCount,
    Integer outdatedSourceRiskCount,
    Integer structuredBusinessDriftRiskCount,
    Integer customerAcquisitionEvidenceCount,
    Integer emotionalOutcomeEvidenceCount,
    Integer autonomousProfessionalFitScore,
    Integer behavioralEvidenceScore,
    Integer sourceFreshnessScore,
    Integer outdatedSourceRiskScore,
    Integer structuredBusinessDriftRiskScore,
    Integer profileSolutionLanguageRiskScore,
    Instant createdAt) {}
