CREATE TABLE codex_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codex_request_id BIGINT NOT NULL,
    sandbox_interaction_id VARCHAR(191) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    content LONGTEXT NOT NULL,
    token_count INT,
    sequence INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_codex_interactions_request FOREIGN KEY (codex_request_id) REFERENCES codex_requests(id)
);

CREATE UNIQUE INDEX uq_codex_interactions_sandbox_id ON codex_interactions(sandbox_interaction_id);
CREATE INDEX idx_codex_interactions_request_sequence ON codex_interactions(codex_request_id, sequence);
