CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org VARCHAR(120) NOT NULL,
    repo VARCHAR(200) NOT NULL UNIQUE,
    is_private BOOLEAN NOT NULL DEFAULT TRUE,
    repo_url LONGVARCHAR,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo VARCHAR(200) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    delivery_id VARCHAR(100) NOT NULL,
    payload LONGTEXT NOT NULL,
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_events_repo ON events(repo);
CREATE INDEX idx_events_received_at ON events(received_at);

CREATE TABLE runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo VARCHAR(200) NOT NULL,
    run_id BIGINT NOT NULL,
    attempt INT NOT NULL DEFAULT 1,
    status VARCHAR(60),
    conclusion VARCHAR(60),
    workflow_name VARCHAR(200),
    logs_url LONGVARCHAR,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_runs UNIQUE (repo, run_id, attempt)
);
CREATE INDEX idx_runs_repo ON runs(repo);
CREATE INDEX idx_runs_created_at ON runs(created_at);

CREATE TABLE prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo VARCHAR(200) NOT NULL,
    run_id BIGINT,
    pr_number INT,
    model VARCHAR(100) NOT NULL,
    prompt LONGTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_prompts_repo ON prompts(repo);

CREATE TABLE responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_id BIGINT,
    repo VARCHAR(200) NOT NULL,
    run_id BIGINT,
    pr_number INT,
    root_cause LONGTEXT,
    fix_plan LONGTEXT,
    unified_diff LONGTEXT,
    confidence DECIMAL(5,2),
    raw_response LONGTEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_responses_prompt FOREIGN KEY (prompt_id) REFERENCES prompts(id) ON DELETE CASCADE
);
CREATE INDEX idx_responses_repo ON responses(repo);


CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(120) NOT NULL,
    action VARCHAR(120) NOT NULL,
    target VARCHAR(200),
    payload LONGVARCHAR,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_created_at ON audit_log(created_at);
