CREATE TABLE environment_containers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment_id BIGINT NOT NULL,
    name VARCHAR(191) NOT NULL,
    container_identifier VARCHAR(191),
    ip_address VARCHAR(191) NOT NULL,
    port INT NOT NULL,
    source VARCHAR(20) NOT NULL,
    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_environment_containers_environment FOREIGN KEY (environment_id)
        REFERENCES environments (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX uk_env_container_name_port ON environment_containers (environment_id, name, port);
CREATE INDEX idx_env_containers_environment ON environment_containers (environment_id);
