CREATE TABLE prompt_hints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(150) NOT NULL,
    phrase LONGTEXT NOT NULL,
    environment_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE prompt_hints
    ADD CONSTRAINT fk_prompt_hints_environment FOREIGN KEY (environment_id) REFERENCES environments(id) ON DELETE CASCADE;

CREATE INDEX idx_prompt_hints_environment ON prompt_hints(environment_id);
