package com.marketinghub.nichocnae.routinequalitygate;

import java.time.Instant;

/** Representa o insumo de avaliação de qualidade recebido do backend para a etapa sete. */
public record RoutineQualityGatePending(
        Long routineCardId,
        Long researchCycleId,
        String nicheName,
        String routineSummary,
        String painsSummary,
        String resultsSummary,
        String mechanismOpportunitiesSummary,
        String customerBehaviorSummary,
        String channelsSummary,
        String evidenceSummary,
        String sourceDomains,
        Integer cardConfidenceScore,
        Integer sourceCount,
        Integer signalCount,
        Integer questionSignalCount,
        Integer painSignalCount,
        Integer operationalDifficultyCount,
        Integer mechanismOpportunityCount,
        Integer routineTaskCount,
        Integer commercialObjectCount,
        Integer languageMarkerCount,
        Integer solutionLanguageRiskCount,
        Integer routineEvidenceScore,
        Integer difficultyEvidenceScore,
        Integer sourceDiversityScore,
        Integer solutionLanguageRiskScore,
        Integer brazilianSourceCount,
        Integer recentSourceCount,
        Integer outdatedSourceRiskCount,
        Integer structuredBusinessDriftRiskCount,
        Integer customerAcquisitionEvidenceCount,
        Integer emotionalOutcomeEvidenceCount,
        Integer autonomousProfessionalFitScore,
        Integer behavioralEvidenceScore,
        Integer sourceFreshnessScore,
        Integer outdatedSourceRiskScore,
        Integer structuredBusinessDriftRiskScore,
        Integer profileSolutionLanguageRiskScore,
        Instant createdAt) {}
