export const PROMPT_DOMAINS = [
  {
    value: "NICHE_DETAILED_DESCRIPTION",
    label: "Descrição detalhada de nicho",
  },
  {
    value: "NICHE_HYPOTHESIS",
    label: "Geração de hipóteses de nicho",
  },
];

export const PROMPT_VARIABLES: Record<string, string[]> = {
  NICHE_DETAILED_DESCRIPTION: [
    "quantity",
    "niche.id",
    "niche.name",
    "niche.description",
    "niche.baseSegmentation",
    "niche.interests",
    "niche.demographicFilters",
    "niche.extraTips",
    "niche.interestCategory",
    "niche.roleCategory",
  ],
  NICHE_HYPOTHESIS: [
    "quantity",
    "niche.id",
    "niche.name",
    "niche.description",
    "niche.baseSegmentation",
    "niche.interests",
    "niche.demographicFilters",
    "niche.extraTips",
    "niche.interestCategory",
    "niche.roleCategory",
    "detailedDescription.id",
    "detailedDescription.title",
    "detailedDescription.description",
    "detailedDescription.pains",
    "detailedDescription.desires",
    "detailedDescription.needs",
    "detailedDescription.model",
    "detailedDescription.prompt",
    "detailedDescription.createdAt",
    "detailedDescription.updatedAt",
    "technology.id",
    "technology.name",
    "technology.description",
    "technology.promptText",
    "technology.createdAt",
    "technology.updatedAt",
    "niche.detailedDescriptions[].id",
    "niche.detailedDescriptions[].title",
    "niche.detailedDescriptions[].description",
    "niche.detailedDescriptions[].pains",
    "niche.detailedDescriptions[].desires",
    "niche.detailedDescriptions[].needs",
    "niche.detailedDescriptions[].model",
    "niche.detailedDescriptions[].prompt",
    "niche.detailedDescriptions[].createdAt",
    "niche.detailedDescriptions[].updatedAt",
    "niche.latestDetailedDescription.id",
    "niche.latestDetailedDescription.title",
    "niche.latestDetailedDescription.description",
    "niche.latestDetailedDescription.pains",
    "niche.latestDetailedDescription.desires",
    "niche.latestDetailedDescription.needs",
    "niche.latestDetailedDescription.model",
    "niche.latestDetailedDescription.prompt",
    "niche.latestDetailedDescription.createdAt",
    "niche.latestDetailedDescription.updatedAt",
    "niche.hypothesisDetailedDescription.id",
    "niche.hypothesisDetailedDescription.title",
    "niche.hypothesisDetailedDescription.description",
    "niche.hypothesisDetailedDescription.pains",
    "niche.hypothesisDetailedDescription.desires",
    "niche.hypothesisDetailedDescription.needs",
    "niche.hypothesisDetailedDescription.model",
    "niche.hypothesisDetailedDescription.prompt",
    "niche.hypothesisDetailedDescription.createdAt",
    "niche.hypothesisDetailedDescription.updatedAt",
    "niche.differentiatedTechnology.id",
    "niche.differentiatedTechnology.name",
    "niche.differentiatedTechnology.description",
    "niche.differentiatedTechnology.promptText",
    "niche.differentiatedTechnology.createdAt",
    "niche.differentiatedTechnology.updatedAt",
    "attributes[].id",
    "attributes[].name",
    "attributes[].description",
    "attributeNames",
    "defaultAttributes",
  ],
};
