import assert from 'node:assert/strict';
const base='http://127.0.0.1:18080/api/pde/vega/private/v1';const internal='vega-local-internal-only';
let controls=0;
const request=async(path,body,token,method)=>{const response=await fetch(base+path,{method:method||(body===undefined?'GET':'POST'),headers:{'Content-Type':'application/json',...(token?{'X-Vega-Session':token}:{'X-PDE-Internal-Token':internal})},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await response.json();}catch{}return {status:response.status,data};};
const check=(condition,label)=>{assert.ok(condition,label);controls++;console.log('PASS',label);};
const create=async(origin='QA_INTERNAL',readingNumber)=>{let r=await request('/internal/sessions',{cycleId:91002,prototypeVersion:'musa-pde-entry-v9-primeiro-ajuste-aplicavel',origin,readingNumber});assert.equal(r.status,200);return r.data;};
const waitResult=async(token)=>{for(let i=0;i<40;i++){let r=await request('/session',undefined,token);if(['COMPLETED','FAILED','BLOCKED'].includes(r.data.generationStatus))return r.data;await new Promise(r=>setTimeout(r,500));}throw new Error('Timeout da geração local');};
check((await request('/session',undefined,'invalid')).status===401,'acesso inválido rejeitado');
check((await fetch(base+'/internal/cycles/91002/report')).status===401,'relatório protegido');
check((await request('/internal/sessions',{cycleId:91002,prototypeVersion:'historical-v7',origin:'QA_INTERNAL'})).status===409,'versão alheia rejeitada');
const a=await create(),b=await create();
check(a.id!==b.id && a.sessionToken!==b.sessionToken,'sessões segregadas');
check(Object.keys(a.events).length===0,'abrir sessão não emite início');
check((await request('/generate',{occasion:'Almoço informal',existingSelection:'Camisa'},a.sessionToken)).status===409,'geração exige início explícito');
await request('/start',{},a.sessionToken);await request('/start',{},a.sessionToken);
check(Object.keys((await request('/session',undefined,a.sessionToken)).data.events).length===1,'início idempotente');
check((await request('/generate',{occasion:'',existingSelection:''},a.sessionToken)).status===400,'campos obrigatórios validados');
check((await request('/events',{eventType:'VALUE_MOMENT',answer:'sim'},a.sessionToken)).status===409,'valor não existe sem cartão');
const payload={occasion:'Almoço informal',existingSelection:'Camisa branca',optionalNote:'TEST_INVALID'};
await request('/generate',payload,a.sessionToken);let failed=await waitResult(a.sessionToken);
check(failed.generationStatus==='FAILED'&&!failed.card && !failed.events.VALUE_MOMENT,'schema inválido não vira valor');
await request('/generate',{...payload,optionalNote:'TEST_503'},a.sessionToken);failed=await waitResult(a.sessionToken);
check(failed.generationStatus==='FAILED'&&failed.error.includes('503'),'falha de provedor preserva causa');
const duplicates=await Promise.all(Array.from({length:5},()=>request('/generate',{...payload,optionalNote:''},a.sessionToken)));
const generated=duplicates[0],duplicate=duplicates[1];
check(duplicates.every(r=>r.status===200&&r.data.executionId===generated.data.executionId),'concorrência preserva uma única tentativa');
check(generated.data.executionId===duplicate.data.executionId,'clique repetido não duplica inferência');
let result=await waitResult(a.sessionToken);check(result.generationStatus==='COMPLETED'&&!!result.card.application,'cartão completo após nova tentativa');
const repeated=await request('/generate',{...payload,optionalNote:'Outra nota'},a.sessionToken);
check(repeated.data.card.cardId===result.card.cardId,'retomada não regenera resultado pronto');
check((await request('/session',undefined,b.sessionToken)).data.card==null,'outra sessão não recebe cartão');
check((await request('/events',{eventType:'READY_RESULT_USED',answer:'sim'},a.sessionToken)).status===409,'uso exige compreensão');
await request('/events',{eventType:'VALUE_MOMENT',answer:'Entendi'},a.sessionToken);
check((await request('/events',{eventType:'READY_RESULT_USED',answer:''},a.sessionToken)).status===409,'uso exige autoavaliação');
await request('/events',{eventType:'READY_RESULT_USED',answer:'Confortável'},a.sessionToken);
await request('/events',{eventType:'PREFERENCE',answer:'FREE'},a.sessionToken);
result=(await request('/session',undefined,a.sessionToken)).data;
check(!result.events.PREFERRED_OVER_FREE,'alternativa gratuita não gera preferência pelo produto');
await request('/events',{eventType:'CHECKOUT_STARTED',answer:'Simular'},a.sessionToken);
await request('/events',{eventType:'CHECKOUT_STARTED',answer:'Simular'},a.sessionToken);
result=(await request('/finish',{},a.sessionToken)).data;
check(result.card.cardId===repeated.data.card.cardId && !result.paymentEnabled && !result.published,'encerramento mantém resultado sem venda');
let report=(await request('/internal/cycles/91002/report')).data;let own=report.readings.find(r=>r.id===a.id);
check(own.executions.length===3&&own.executions[0].status==='FAILED'&&own.executions[2].request&&own.executions[2].rawResponse,'histórico e auditoria de cada tentativa preservados');
const human=await create('HUMAN',1);
check((await request('/internal/sessions',{cycleId:91002,prototypeVersion:human.prototypeVersion,origin:'HUMAN',readingNumber:1})).status===409,'convite humano único por leitura');
check((await request('/access',{accessToken:human.accessToken,consentAccepted:false})).status===400,'convite exige consentimento');
const login=(await request('/access',{accessToken:human.accessToken,consentAccepted:true})).data;
await request('/start',{},login.sessionToken);
const login2=(await request('/access',{accessToken:human.accessToken,consentAccepted:true})).data;
check(login2.id===human.id&&login2.events.EXPERIENCE_STARTED,'retomada pelo convite preserva leitura');
check((await request('/session',undefined,login.sessionToken)).status===401,'nova autenticação invalida sessão antiga');
await request('/internal/sessions/'+human.id,undefined,undefined,'DELETE');
check((await request('/session',undefined,login2.sessionToken)).status===401,'revogação bloqueia sessão e convite');
report=(await request('/internal/cycles/91002/report')).data;
check(report.humanReadings>=1&&report.testReadings>=2&&report.sales===0,'métricas separam participantes e tráfego de teste');
console.log('CONTROLES',controls);
