package com.marketinghub.leadportal.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

/**
 * Normalizes the custom HTML payload stored in flows, extracting the actual HTML document
 * from structured JSON responses generated by the experiments pipeline.
 */
@Component
public class CustomFormHtmlResolver {

    private static final Pattern HTML_HINT = Pattern.compile("(?is)^\\s*(?:<!doctype|<html|<body|<main|<section|<div|<header|<footer)");
    private static final Pattern FENCED_JSON = Pattern.compile("```(?:json)?\\s*([\\s\\S]*?)```", Pattern.CASE_INSENSITIVE);
    private static final Pattern HTML_DOCUMENT_PATTERN = Pattern.compile("\\\"htmlDocument\\\"\\s*:\\s*\\\"((?:\\\\.|[^\\\\\\\"])*)\\\"", Pattern.CASE_INSENSITIVE);

    private final ObjectMapper objectMapper;

    public CustomFormHtmlResolver(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    /**
     * Attempts to extract the HTML document from the supplied payload. When no HTML is detected,
     * the original trimmed value is returned to keep backwards compatibility.
     */
    public String normalize(String rawValue) {
        if (!StringUtils.hasText(rawValue)) {
            return null;
        }
        String trimmed = rawValue.trim();
        if (looksLikeHtml(trimmed)) {
            return trimmed;
        }
        String extracted = extractHtmlFromJson(trimmed);
        if (StringUtils.hasText(extracted)) {
            return extracted.trim();
        }
        return trimmed;
    }

    private String extractHtmlFromJson(String payload) {
        JsonNode root = parseJson(payload);
        if (root == null) {
            String embedded = extractEmbeddedJson(payload);
            if (embedded != null) {
                root = parseJson(embedded);
            }
        }
        if (root == null) {
            return extractHtmlWithPattern(payload);
        }
        JsonNode htmlNode = locateHtmlDocumentNode(root);
        if (htmlNode != null && !htmlNode.isMissingNode() && htmlNode.isTextual()) {
            String candidate = htmlNode.asText();
            if (StringUtils.hasText(candidate)) {
                String normalized = candidate.trim();
                if (looksLikeHtml(normalized)) {
                    return normalized;
                }
                if (looksLikeJsonCandidate(normalized)) {
                    return extractHtmlFromJson(normalized);
                }
                return normalized;
            }
        }
        return extractHtmlWithPattern(payload);
    }

    private JsonNode locateHtmlDocumentNode(JsonNode root) {
        if (root == null) {
            return null;
        }
        JsonNode landing = root.at("/landingPageHtml/htmlDocument");
        if (!landing.isMissingNode()) {
            return landing;
        }
        JsonNode artifact = root.at("/artifact/content/htmlDocument");
        if (!artifact.isMissingNode()) {
            return artifact;
        }
        return root.findValue("htmlDocument");
    }

    private JsonNode parseJson(String source) {
        if (!looksLikeJsonCandidate(source)) {
            return null;
        }
        try {
            return objectMapper.readTree(source);
        } catch (JsonProcessingException ex) {
            return null;
        }
    }

    private String extractHtmlWithPattern(String payload) {
        if (!StringUtils.hasText(payload)) {
            return null;
        }
        Matcher matcher = HTML_DOCUMENT_PATTERN.matcher(payload);
        if (!matcher.find()) {
            return null;
        }
        String raw = matcher.group(1);
        String unescaped = unescapeJsonString(raw);
        if (!StringUtils.hasText(unescaped)) {
            return null;
        }
        String normalized = unescaped.trim();
        if (looksLikeHtml(normalized)) {
            return normalized;
        }
        return normalized;
    }

    private String unescapeJsonString(String value) {
        if (!StringUtils.hasText(value)) {
            return value;
        }
        try {
            return objectMapper.readValue("\"" + value + "\"", String.class);
        } catch (JsonProcessingException ex) {
            return value;
        }
    }

    private String extractEmbeddedJson(String text) {
        if (!StringUtils.hasText(text)) {
            return null;
        }
        Matcher fenced = FENCED_JSON.matcher(text);
        if (fenced.find()) {
            return fenced.group(1);
        }
        int firstBrace = text.indexOf('{');
        int lastBrace = text.lastIndexOf('}');
        if (firstBrace >= 0 && lastBrace > firstBrace) {
            return text.substring(firstBrace, lastBrace + 1);
        }
        return null;
    }

    private boolean looksLikeHtml(String value) {
        return HTML_HINT.matcher(value).find();
    }

    private boolean looksLikeJsonCandidate(String value) {
        if (!StringUtils.hasText(value)) {
            return false;
        }
        String trimmed = value.trim();
        return trimmed.startsWith("{") || trimmed.startsWith("[");
    }
}
