package com.marketinghub.agenttask;

import java.time.Instant;

/** Responsabilidade: expor uma tarefa com identidades legíveis e técnicas dos agentes. */
public record AgentTaskResponse(
    Long id,
    Long assignedAgentId,
    String assignedAgentKey,
    String assignedAgentNickname,
    String requestedByType,
    Long requestedByAgentId,
    String requestedByAgentKey,
    String requestedByName,
    String title,
    String description,
    String priority,
    String status,
    String sourceReference,
    Long processDefinitionId,
    String processCode,
    Integer processVersionNumber,
    String processActivityId,
    String processActivityName,
    boolean exceptional,
    String exceptionReason,
    String taskKind,
    String gateCode,
    String gateStatus,
    String gateDecisionReason,
    Instant gateDecidedAt,
    Instant receivedAt,
    Instant deliveredAt,
    Instant createdAt,
    Instant updatedAt) {

  /** Mantém compatibilidade de testes e integrações internas anteriores ao vínculo BPM. */
  public AgentTaskResponse(
      Long id,
      Long assignedAgentId,
      String assignedAgentKey,
      String assignedAgentNickname,
      String requestedByType,
      Long requestedByAgentId,
      String requestedByAgentKey,
      String requestedByName,
      String title,
      String description,
      String priority,
      String status,
      String sourceReference,
      String taskKind,
      String gateCode,
      String gateStatus,
      String gateDecisionReason,
      Instant gateDecidedAt,
      Instant createdAt,
      Instant updatedAt) {
    this(
        id,
        assignedAgentId,
        assignedAgentKey,
        assignedAgentNickname,
        requestedByType,
        requestedByAgentId,
        requestedByAgentKey,
        requestedByName,
        title,
        description,
        priority,
        status,
        sourceReference,
        null,
        null,
        null,
        null,
        null,
        false,
        null,
        taskKind,
        gateCode,
        gateStatus,
        gateDecisionReason,
        gateDecidedAt,
        createdAt,
        null,
        createdAt,
        updatedAt);
  }
}
