package com.marketinghub.pdemonitor.db;

import static org.assertj.core.api.Assertions.assertThat;

import com.marketinghub.pdemonitor.health.PdeHealthResult;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.UUID;
import javax.sql.DataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

/** Valida o acesso direto às tabelas operacionais usadas pelo monitor de PDEs. */
class PdeMonitorRepositoryTest {
    private JdbcTemplate jdbcTemplate;
    private PdeMonitorRepository repository;

    @BeforeEach
    /** Prepara um banco isolado em memória para cada cenário de repositório. */
    void setUp() {
        DataSource dataSource =
                new EmbeddedDatabaseBuilder()
                        .setName("pde-monitor-" + UUID.randomUUID())
                        .setType(EmbeddedDatabaseType.H2)
                        .build();
        jdbcTemplate = new JdbcTemplate(dataSource);
        repository = new PdeMonitorRepository(jdbcTemplate);
        createSchema();
    }

    @Test
    /** Garante que somente PDEs críticos habilitados entram no ciclo 24/7. */
    void deveListarSomentePdesCriticosHabilitados() {
        insertModule(1, "pde-musa-v6", "PDE", "CRITICAL", true);
        insertModule(2, "backend", "BACKEND", "CRITICAL", true);
        insertModule(3, "pde-musa-v5", "PDE", "HIGH", true);
        insertModule(4, "pde-antigo", "PDE", "CRITICAL", false);

        var modules = repository.findCriticalPdes();

        assertThat(modules).extracting(PdeMonitoredModule::code).containsExactly("pde-musa-v6");
    }

    @Test
    /** Garante gravação direta de heartbeat e abertura de incidente. */
    void deveGravarHeartbeatEAbrirIncidente() {
        insertModule(1, "pde-musa-v6", "PDE", "CRITICAL", true);
        var module = repository.findCriticalPdes().getFirst();
        var checkedAt = Instant.parse("2026-07-28T10:00:00Z");

        repository.insertHealthCheck(
                module, new PdeHealthResult(checkedAt, "OFFLINE", null, 250, null, "TimeoutException"));
        repository.openIncident(
                module, new PdeHealthResult(checkedAt, "OFFLINE", null, 250, null, "TimeoutException"), "CRITICAL");

        Integer checks =
                jdbcTemplate.queryForObject("SELECT COUNT(*) FROM ops_module_health_check", Integer.class);
        Integer incidents =
                jdbcTemplate.queryForObject("SELECT COUNT(*) FROM ops_module_incident WHERE status = 'OPEN'", Integer.class);
        assertThat(checks).isEqualTo(1);
        assertThat(incidents).isEqualTo(1);
    }

    @Test
    /** Garante que incidentes abertos são encerrados com duração calculada. */
    void deveEncerrarIncidenteAberto() {
        insertModule(1, "pde-musa-v6", "PDE", "CRITICAL", true);
        var startedAt = Instant.parse("2026-07-28T10:00:00Z");
        jdbcTemplate.update(
                """
                INSERT INTO ops_module_incident
                  (id, module_id, status, severity, started_at, summary, root_signal, last_error)
                VALUES (99, 1, 'OPEN', 'CRITICAL', ?, 'falha', 'PDE_HTTP_OFFLINE', 'erro')
                """,
                Timestamp.from(startedAt));

        repository.closeIncident(99, Instant.parse("2026-07-28T10:02:00Z"), startedAt);

        var status =
                jdbcTemplate.queryForObject("SELECT status FROM ops_module_incident WHERE id = 99", String.class);
        var duration =
                jdbcTemplate.queryForObject("SELECT duration_seconds FROM ops_module_incident WHERE id = 99", Long.class);
        assertThat(status).isEqualTo("RESOLVED");
        assertThat(duration).isEqualTo(120);
    }

    /** Cria o subconjunto do schema operacional usado pelos testes do repositório. */
    private void createSchema() {
        jdbcTemplate.execute(
                """
                CREATE TABLE ops_monitored_module (
                  id BIGINT NOT NULL,
                  code VARCHAR(100) NOT NULL,
                  name VARCHAR(150) NOT NULL,
                  type VARCHAR(50) NOT NULL,
                  base_url VARCHAR(512) NOT NULL,
                  health_path VARCHAR(255) NOT NULL,
                  monitoring_url VARCHAR(512),
                  enabled TINYINT NOT NULL,
                  criticality VARCHAR(30) NOT NULL,
                  offline_threshold_seconds INT NOT NULL,
                  PRIMARY KEY (id)
                )
                """);
        jdbcTemplate.execute(
                """
                CREATE TABLE ops_module_health_check (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  module_id BIGINT NOT NULL,
                  checked_at TIMESTAMP NOT NULL,
                  status VARCHAR(30) NOT NULL,
                  http_status INT,
                  response_time_ms BIGINT,
                  error_message VARCHAR(1000),
                  raw_payload CLOB
                )
                """);
        jdbcTemplate.execute(
                """
                CREATE TABLE ops_module_incident (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  module_id BIGINT NOT NULL,
                  status VARCHAR(30) NOT NULL,
                  severity VARCHAR(30) NOT NULL,
                  started_at TIMESTAMP NOT NULL,
                  ended_at TIMESTAMP,
                  duration_seconds BIGINT,
                  summary VARCHAR(500) NOT NULL,
                  root_signal VARCHAR(255),
                  last_error VARCHAR(1000),
                  updated_at TIMESTAMP
                )
                """);
    }

    /** Insere um módulo monitorado para compor cenários de seleção. */
    private void insertModule(long id, String code, String type, String criticality, boolean enabled) {
        jdbcTemplate.update(
                """
                INSERT INTO ops_monitored_module
                  (id, code, name, type, base_url, health_path, monitoring_url, enabled, criticality, offline_threshold_seconds)
                VALUES (?, ?, ?, ?, 'https://example.test', '/healthz', 'https://example.test/?mh_monitor=1', ?, ?, 120)
                """,
                id,
                code,
                code,
                type,
                enabled ? 1 : 0,
                criticality);
    }
}
