services:
  oprm-coletor-mei:
    image: ${OPRM_COLETOR_MEI_IMAGE}
    build: null
    environment:
      - OPRM_COLLECTOR_SCHEDULE_PAYLOAD_FILE=${OPRM_COLLECTOR_SCHEDULE_PAYLOAD_FILE:-/app/config/receita-cnaes.json}
