package com.marketinghub.worker.successproduct;

import com.marketinghub.niche.dto.CreateMarketNicheRequest;
import com.marketinghub.niche.MarketNiche;
import com.marketinghub.niche.service.MarketNicheService;
import com.marketinghub.hypothesis.dto.CreateHypothesisRequest;
import com.marketinghub.hypothesis.service.HypothesisService;
import com.marketinghub.worker.WorkerSuccessProductRepository;
import com.marketinghub.successproduct.SuccessProduct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.util.List;

/**
 * Generates {@link com.marketinghub.niche.MarketNiche} and
 * {@link com.marketinghub.hypothesis.Hypothesis} entities from existing
 * {@link SuccessProduct} records.
 *
 * <p>The niche and hypothesis are generated by querying ChatGPT with the
 * success product's description.</p>
 */
@Service
public class SuccessProductNicheHypothesisService {
    private static final Logger log = LoggerFactory.getLogger(SuccessProductNicheHypothesisService.class);
    private final WorkerSuccessProductRepository productRepository;
    private final MarketNicheService marketNicheService;
    private final HypothesisService hypothesisService;
    private final ChatGptClient chatGptClient;

    public SuccessProductNicheHypothesisService(WorkerSuccessProductRepository productRepository,
                                               MarketNicheService marketNicheService,
                                               HypothesisService hypothesisService,
                                               ChatGptClient chatGptClient) {
        this.productRepository = productRepository;
        this.marketNicheService = marketNicheService;
        this.hypothesisService = hypothesisService;
        this.chatGptClient = chatGptClient;
    }

    /**
     * Process all success products flagged for generation and create corresponding
     * niche and hypothesis entries.
     */
    @Transactional
    public void generate() {
        List<SuccessProduct> products = productRepository.findByGenerateNicheHypothesisTrue();
        log.info("Processing {} success products for niche/hypothesis generation", products.size());
        for (SuccessProduct product : products) {
            if (product.getDescription() == null || product.getDescription().isBlank()) {
                log.debug("Skipping product {} due to missing description", product.getId());
                continue;
            }

            ChatGptClient.NicheHypothesis data = chatGptClient.extract(product);
            if (data == null || data.nicheName() == null || data.hypothesisTitle() == null) {
                log.warn("ChatGPT returned incomplete data for product {}", product.getId());
                continue;
            }

            CreateMarketNicheRequest nicheReq = new CreateMarketNicheRequest();
            nicheReq.setName(data.nicheName());
            nicheReq.setDescription(data.nicheDescription());
            MarketNiche niche = marketNicheService.create(nicheReq);

            CreateHypothesisRequest hypReq = new CreateHypothesisRequest();
            hypReq.setMarketNicheId(niche.getId());
            hypReq.setTitle(data.hypothesisTitle());
            if (StringUtils.hasText(data.persona())) {
                hypReq.setPersona(data.persona());
            } else {
                hypReq.setPersona(resolveDefaultPersona(niche));
            }
            hypReq.setProblem(data.problem());
            hypReq.setPromise(data.promise());
            hypReq.setUniqueMechanism(data.uniqueMechanism());
            hypothesisService.create(hypReq);

            log.info("Resetting generateNicheHypothesis for product {}", product.getId());
            product.setGenerateNicheHypothesis(false);
            productRepository.save(product);
        }
    }

    private static String resolveDefaultPersona(MarketNiche niche) {
        if (niche != null) {
            String idLabel = niche.getId() != null ? " (ID " + niche.getId() + ")" : "";
            if (StringUtils.hasText(niche.getName())) {
                return "Público geral do nicho " + niche.getName() + idLabel;
            }
            return "Público geral do nicho" + idLabel;
        }
        return "Público geral do nicho";
    }
}
