package com.marketinghub.worker.creative.pipeline;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.marketinghub.experiment.Experiment;
import java.lang.reflect.Method;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.util.StringUtils;

/**
 * Utility responsible for translating the structured pipeline outputs into
 * ad creative plans.
 */
public class ExperimentPipelineAdExtractor {
    private static final Logger log = LoggerFactory.getLogger(ExperimentPipelineAdExtractor.class);

    private final ObjectMapper objectMapper;

    /**
     * Creates the extractor with the JSON mapper used to inspect pipeline artifacts.
     */
    public ExperimentPipelineAdExtractor(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    /**
     * Extracts ad creative plans from direct, nested or embedded JSON generated by the pipeline.
     */
    public List<PipelineAdCreativePlan> extract(Experiment experiment) {
        String adCopyRaw = readStringField(experiment, "getAdCopy");
        if (experiment == null || !StringUtils.hasText(adCopyRaw)) {
            return List.of();
        }
        JsonNode variants = findVariants(adCopyRaw);
        if (variants == null || !variants.isArray()) {
            return List.of();
        }
        List<PipelineImageBriefing> orderedBriefings = new ArrayList<>();
        Map<String, PipelineImageBriefing> briefingsByKey =
                extractImageBriefings(readStringField(experiment, "getAdImageBriefing"), orderedBriefings);
        List<PipelineAdCreativePlan> plans = new ArrayList<>();
        int index = 0;
        for (JsonNode variant : variants) {
            PipelineAdCreativePlan plan = toPlan(variant, index++, briefingsByKey, orderedBriefings);
            if (plan != null) {
                plans.add(plan);
            }
        }
        return plans;
    }

    /**
     * Finds primary text variants in all object candidates, including JSON embedded in text fields.
     */
    private JsonNode findVariants(String rawJson) {
        for (JsonNode candidate : collectObjectCandidates(rawJson)) {
            JsonNode scope = candidate.hasNonNull("adCopy") && candidate.get("adCopy").isObject()
                    ? candidate.get("adCopy")
                    : candidate;
            JsonNode variants = firstArray(scope, "primaryTextVariants", "variants");
            if (variants != null) {
                return variants;
            }
        }
        return null;
    }


    /**
     * Reads string properties through reflection so the worker stays compatible with the backend model artifact.
     */
    private String readStringField(Object target, String getterName) {
        if (target == null || !StringUtils.hasText(getterName)) {
            return null;
        }
        try {
            Method getter = target.getClass().getMethod(getterName);
            Object value = getter.invoke(target);
            return value instanceof String ? (String) value : null;
        } catch (Exception ex) {
            Long experimentId = target instanceof Experiment experiment ? experiment.getId() : null;
            log.debug("Falha ao ler campo textual do pipeline no worker. experimentId={} getter={}",
                    experimentId, getterName, ex);
            return null;
        }
    }

    /**
     * Parses a raw JSON object or returns null while logging invalid pipeline payloads for diagnosis.
     */
    private JsonNode parse(String rawJson) {
        if (!StringUtils.hasText(rawJson)) {
            return null;
        }
        try {
            return objectMapper.readTree(rawJson);
        } catch (Exception ex) {
            log.debug("Falha ao interpretar JSON do pipeline de anúncios. payloadLength={}", rawJson.length(), ex);
            return null;
        }
    }

    /**
     * Collects object candidates recursively from direct JSON, fenced JSON and JSON strings nested inside objects.
     */
    private List<JsonNode> collectObjectCandidates(String rawJson) {
        JsonNode parsed = parse(rawJson);
        if (parsed == null) {
            parsed = parseEmbeddedJson(rawJson);
        }
        if (parsed == null) {
            return List.of();
        }
        List<JsonNode> candidates = new ArrayList<>();
        collectObjectCandidates(parsed, candidates);
        return candidates;
    }

    /**
     * Walks a parsed JSON tree and appends every object that can contain pipeline contract fields.
     */
    private void collectObjectCandidates(JsonNode node, List<JsonNode> candidates) {
        if (node == null) {
            return;
        }
        if (node.isObject()) {
            candidates.add(node);
            node.fields().forEachRemaining(entry -> {
                JsonNode value = entry.getValue();
                collectObjectCandidates(value, candidates);
                if (value != null && value.isTextual()) {
                    JsonNode embedded = parseEmbeddedJson(value.asText());
                    collectObjectCandidates(embedded, candidates);
                }
            });
            return;
        }
        if (node.isArray()) {
            node.forEach(child -> collectObjectCandidates(child, candidates));
            return;
        }
        if (node.isTextual()) {
            JsonNode embedded = parseEmbeddedJson(node.asText());
            collectObjectCandidates(embedded, candidates);
        }
    }

    /**
     * Extracts the first valid JSON object found inside a text field or Markdown code fence.
     */
    private JsonNode parseEmbeddedJson(String text) {
        if (!StringUtils.hasText(text)) {
            return null;
        }
        String fenced = extractFencedJson(text);
        if (StringUtils.hasText(fenced)) {
            JsonNode parsedFence = parse(fenced);
            if (parsedFence != null && parsedFence.isObject()) {
                return parsedFence;
            }
        }
        int firstBrace = text.indexOf('{');
        int lastBrace = text.lastIndexOf('}');
        if (firstBrace >= 0 && lastBrace > firstBrace) {
            JsonNode parsedCandidate = parse(text.substring(firstBrace, lastBrace + 1));
            if (parsedCandidate != null && parsedCandidate.isObject()) {
                return parsedCandidate;
            }
        }
        return null;
    }

    /**
     * Reads a JSON code fence from model output text when present.
     */
    private String extractFencedJson(String text) {
        int fenceStart = text.indexOf("```");
        if (fenceStart < 0) {
            return null;
        }
        int contentStart = text.indexOf('\n', fenceStart + 3);
        if (contentStart < 0) {
            contentStart = fenceStart + 3;
        } else {
            contentStart++;
        }
        int fenceEnd = text.indexOf("```", contentStart);
        if (fenceEnd <= contentStart) {
            return null;
        }
        return text.substring(contentStart, fenceEnd).trim();
    }

    /**
     * Returns the first array stored under one of the accepted contract keys.
     */
    private JsonNode firstArray(JsonNode node, String... keys) {
        if (node == null || !node.isObject()) {
            return null;
        }
        for (String key : keys) {
            JsonNode value = node.get(key);
            if (value != null && value.isArray()) {
                return value;
            }
        }
        return null;
    }

    /**
     * Converts one ad-copy variant plus its matched image briefing into a creative plan.
     */
    private PipelineAdCreativePlan toPlan(JsonNode variant,
                                          int index,
                                          Map<String, PipelineImageBriefing> briefingsByKey,
                                          List<PipelineImageBriefing> orderedBriefings) {
        if (variant == null || !variant.isObject()) {
            return null;
        }
        String label = text(variant, "label", "variant", "mustMatchAdVariant", "openingHookType");
        String normalizedLabel = normalize(label);
        String fallbackLabel = "variant-" + (index + 1);
        String placementHint = text(variant, "placementHint");
        if (!StringUtils.hasText(placementHint)) {
            placementHint = "feed";
        }
        String headline = text(variant, "headline", "title");
        String primaryText = resolvePrimaryText(variant);
        String description = text(variant, "description", "subtitle");
        String ctaText = text(variant, "ctaText", "cta");
        PipelineImageBriefing briefing = pickBriefing(normalizedLabel, briefingsByKey, orderedBriefings);
        String format = resolveFormat(placementHint, briefing);
        return new PipelineAdCreativePlan(
                StringUtils.hasText(label) ? label : fallbackLabel,
                placementHint,
                headline,
                primaryText,
                description,
                ctaText,
                format,
                briefing);
    }

    /**
     * Resolves the Meta creative format from placement hints and visual briefing metadata.
     */
    private String resolveFormat(String placementHint, PipelineImageBriefing briefing) {
        String normalizedPlacement = placementHint != null ? placementHint.toLowerCase(Locale.ROOT) : "";
        String assetType = briefing != null ? briefing.assetType() : null;
        if ((assetType != null && assetType.toLowerCase(Locale.ROOT).contains("story"))
                || normalizedPlacement.contains("story")
                || normalizedPlacement.contains("reel")) {
            return "STORY";
        }
        return "LINK";
    }

    /**
     * Resolves the primary ad text using direct fields first and length variants as fallback.
     */
    private String resolvePrimaryText(JsonNode variant) {
        String direct = text(variant, "primaryText", "text");
        if (StringUtils.hasText(direct)) {
            return direct;
        }
        JsonNode lengths = variant.get("lengthVariants");
        if (lengths != null && lengths.isObject()) {
            String[] preferredOrder = {"media", "curta", "longa"};
            for (String key : preferredOrder) {
                String value = text(lengths, key);
                if (StringUtils.hasText(value)) {
                    return value;
                }
            }
        }
        return null;
    }

    /**
     * Extracts visual briefings from direct, nested or embedded image briefing JSON.
     */
    private Map<String, PipelineImageBriefing> extractImageBriefings(String rawJson,
                                                                     List<PipelineImageBriefing> orderedBriefings) {
        if (!StringUtils.hasText(rawJson)) {
            return Collections.emptyMap();
        }
        JsonNode briefings = null;
        for (JsonNode candidate : collectObjectCandidates(rawJson)) {
            JsonNode scope = candidate.hasNonNull("adImageBriefing") && candidate.get("adImageBriefing").isObject()
                    ? candidate.get("adImageBriefing")
                    : candidate;
            briefings = firstArray(scope, "briefings");
            if (briefings != null) {
                break;
            }
        }
        if (briefings == null || !briefings.isArray()) {
            return Collections.emptyMap();
        }
        Map<String, PipelineImageBriefing> byKey = new LinkedHashMap<>();
        for (JsonNode node : briefings) {
            if (node == null || !node.isObject()) {
                continue;
            }
            PipelineImageBriefing briefing = new PipelineImageBriefing(
                    text(node, "mustMatchAdVariant", "visualAngle"),
                    text(node, "visualAngle"),
                    text(node, "assetType"),
                    readInteger(node.get("imageTextMaxWords")),
                    text(node, "visualBriefing"),
                    text(node, "hierarchy"),
                    text(node, "formatByPlacement"),
                    text(node, "safeMargins"),
                    text(node, "complianceNotes"),
                    text(node, "messageMatchNotes"),
                    readKeywords(node.get("supportingKeywords")));
            orderedBriefings.add(briefing);
            String normalized = normalize(briefing.mustMatchAdVariant());
            if (normalized != null) {
                byKey.putIfAbsent(normalized, briefing);
            }
        }
        return byKey;
    }

    /**
     * Reads the supporting keyword list from an image briefing node.
     */
    private List<String> readKeywords(JsonNode node) {
        if (node == null || !node.isArray()) {
            return List.of();
        }
        List<String> keywords = new ArrayList<>();
        for (JsonNode child : node) {
            String value = child != null ? child.asText(null) : null;
            if (StringUtils.hasText(value)) {
                keywords.add(value.trim());
            }
        }
        return keywords;
    }

    /**
     * Chooses the briefing matching the ad variant label or falls back to the first briefing.
     */
    private PipelineImageBriefing pickBriefing(String normalizedLabel,
                                               Map<String, PipelineImageBriefing> byKey,
                                               List<PipelineImageBriefing> ordered) {
        if (normalizedLabel != null && byKey.containsKey(normalizedLabel)) {
            return byKey.get(normalizedLabel);
        }
        return ordered.isEmpty() ? null : ordered.get(0);
    }

    /**
     * Converts numeric JSON values into integers when the value fits the expected type.
     */
    private Integer readInteger(JsonNode node) {
        if (node == null || !node.canConvertToInt()) {
            return null;
        }
        return node.asInt();
    }

    /**
     * Reads the first non-blank textual field from a JSON object.
     */
    private String text(JsonNode node, String... keys) {
        if (node == null) {
            return null;
        }
        for (String key : keys) {
            JsonNode value = node.get(key);
            if (value != null && value.isTextual()) {
                String text = value.asText();
                if (StringUtils.hasText(text)) {
                    return text.trim();
                }
            }
        }
        return null;
    }

    /**
     * Normalizes labels so ad-copy variants can be paired with image briefings.
     */
    private String normalize(String value) {
        if (!StringUtils.hasText(value)) {
            return null;
        }
        String noDiacritics = Normalizer.normalize(value, Normalizer.Form.NFD)
                .replaceAll("\\p{M}", "");
        String sanitized = noDiacritics.replaceAll("[^A-Za-z0-9]+", "");
        return sanitized.isEmpty() ? null : sanitized.toLowerCase(Locale.ROOT);
    }
}
