package com.marketinghub.nichocnae.sourcefetcher;

import java.time.Instant;

/** Representa o snapshot curto persistido pelo backend para uma fonte coletada na etapa quatro. */
public record SourceSnapshotResponse(
        Long sourceSnapshotId,
        Long researchCycleId,
        Long sourceCandidateId,
        String sourceUrl,
        String sourceDomain,
        String sourceTitle,
        String sourceType,
        String sourceIntent,
        Integer routineEvidenceScore,
        Boolean commercialPageRisk,
        Boolean solutionLanguageRisk,
        String sourceClassificationType,
        Integer sourceFreshnessScore,
        Boolean outdatedSourceRisk,
        Integer brazilRelevanceScore,
        Integer autonomousProfessionalEvidenceScore,
        Boolean structuredBusinessDriftRisk,
        Instant publishedAt,
        String snippet,
        String shortExcerpt,
        Instant fetchedAt,
        String fetchStatus,
        Integer httpStatus,
        String storagePolicy,
        String licenseState,
        String errorMessage,
        Instant createdAt) {
    /** Mantém compatibilidade para respostas de testes que ainda não incluem indicadores de fonte. */
    public SourceSnapshotResponse(
            Long sourceSnapshotId,
            Long researchCycleId,
            Long sourceCandidateId,
            String sourceUrl,
            String sourceDomain,
            String sourceTitle,
            String sourceType,
            String sourceIntent,
            Integer routineEvidenceScore,
            Boolean commercialPageRisk,
            Boolean solutionLanguageRisk,
            String snippet,
            String shortExcerpt,
            Instant fetchedAt,
            String fetchStatus,
            Integer httpStatus,
            String storagePolicy,
            String licenseState,
            String errorMessage,
            Instant createdAt) {
        this(
                sourceSnapshotId,
                researchCycleId,
                sourceCandidateId,
                sourceUrl,
                sourceDomain,
                sourceTitle,
                sourceType,
                sourceIntent,
                routineEvidenceScore,
                commercialPageRisk,
                solutionLanguageRisk,
                null,
                null,
                false,
                null,
                null,
                false,
                null,
                snippet,
                shortExcerpt,
                fetchedAt,
                fetchStatus,
                httpStatus,
                storagePolicy,
                licenseState,
                errorMessage,
                createdAt);
    }
}
