package com.marketinghub.nichocnae.sourcefetcher;

import java.time.Instant;

/** Representa uma fonte candidata pendente para coleta curta pela etapa quatro no coletor OPRM. */
public record SourceFetcherPending(
        Long sourceCandidateId,
        Long researchCycleId,
        Long researchQueryId,
        String sourceUrl,
        String sourceTitle,
        String sourceSnippet,
        String sourceDomain,
        String sourceGroup,
        String sourceIntent,
        Integer routineEvidenceScore,
        Boolean commercialPageRisk,
        Boolean solutionLanguageRisk,
        String sourceClassificationType,
        Integer sourceFreshnessScore,
        Boolean outdatedSourceRisk,
        Integer brazilRelevanceScore,
        Integer autonomousProfessionalEvidenceScore,
        Boolean structuredBusinessDriftRisk,
        Instant publishedAt,
        String searchProvider,
        Integer searchPosition,
        String status,
        Instant createdAt,
        Instant updatedAt) {
    /** Mantém compatibilidade para testes que ainda montam pendências sem classificação de atualidade. */
    public SourceFetcherPending(
            Long sourceCandidateId,
            Long researchCycleId,
            Long researchQueryId,
            String sourceUrl,
            String sourceTitle,
            String sourceSnippet,
            String sourceDomain,
            String sourceGroup,
            String sourceIntent,
            Integer routineEvidenceScore,
            Boolean commercialPageRisk,
            Boolean solutionLanguageRisk,
            String searchProvider,
            Integer searchPosition,
            String status,
            Instant createdAt,
            Instant updatedAt) {
        this(
                sourceCandidateId,
                researchCycleId,
                researchQueryId,
                sourceUrl,
                sourceTitle,
                sourceSnippet,
                sourceDomain,
                sourceGroup,
                sourceIntent,
                routineEvidenceScore,
                commercialPageRisk,
                solutionLanguageRisk,
                null,
                null,
                false,
                null,
                null,
                false,
                null,
                searchProvider,
                searchPosition,
                status,
                createdAt,
                updatedAt);
    }
}
