package com.marketinghub.videomanagement.client.dto;

import java.math.BigDecimal;

/** Responsabilidade: representar um ciclo aguardando preflight oficial no executor de vídeo. */
public record ProviderPreflightJob(
        Long preflightId,
        Long cycleId,
        String aggregatorName,
        String accountKey,
        String productionProfile,
        String providerPlan,
        BigDecimal maxCredits,
        Integer targetDurationSeconds,
        Integer providerClipDurationSeconds,
        Integer generationClipCount,
        String aspectRatio,
        String resolution,
        boolean audio,
        String title,
        String objective,
        String hookText,
        String scriptText,
        String scenePlan,
        String characterBible,
        String environmentBible,
        String objectBible,
        String visualStyleGuide,
        String continuityRules,
        String captionPlan,
        String ctaText,
        String characterPerformanceType,
        String characterPerformanceUri,
        String referencePerformanceUri,
        String performanceConsentEvidence,
        String performanceRightsEvidence,
        String editingNotes,
        String qualityGate,
        String learningObjective,
        String successCriterion) {}
