import readline from 'node:readline';
const base=required('MCP_BACKEND_URL').replace(/\/$/,''); const evaluationId=required('MCP_EVALUATION_ID');
const tools=[{name:'consultar_contexto_cliente',description:'Consulta o contexto congelado da avaliação do cliente.',inputSchema:{type:'object',additionalProperties:false,properties:{}}},memoryReadTool(),memoryWriteTool()];
const input=readline.createInterface({input:process.stdin,crlfDelay:Infinity}); input.on('line',async line=>{let request;try{request=JSON.parse(line);const result=await dispatch(request);if(request.id!==undefined)send({jsonrpc:'2.0',id:request.id,result});}catch(error){if(request?.id!==undefined)send({jsonrpc:'2.0',id:request.id,error:{code:-32000,message:error.message}});}});
async function dispatch(request){if(request.method==='initialize')return{protocolVersion:request.params?.protocolVersion??'2025-03-26',capabilities:{tools:{}},serverInfo:{name:'customer-agent',version:'1.1.0'}};if(request.method==='tools/list')return{tools};if(request.method==='ping'||request.method?.startsWith('notifications/'))return{};if(request.method!=='tools/call')throw new Error('Ferramenta não permitida');if(request.params?.name==='recuperar_memoria_especializada')return callMemory('GET',request.params.arguments??{});if(request.params?.name==='registrar_aprendizado_candidato')return callMemory('POST',request.params.arguments??{});if(request.params?.name!=='consultar_contexto_cliente')throw new Error('Ferramenta não permitida');const path=`/api/customer-agent/v1/internal/evaluations/${encodeURIComponent(evaluationId)}`;const response=await fetch(base+path,{headers:{Accept:'application/json'},signal:AbortSignal.timeout(30000)});process.stderr.write(JSON.stringify({tool:'consultar_contexto_cliente',evaluationId,path,status:response.status,at:new Date().toISOString()})+'\n');if(!response.ok)throw new Error(`Backend respondeu HTTP ${response.status}`);return{content:[{type:'text',text:await response.text()}]};}
function memoryReadTool(){return{name:'recuperar_memoria_especializada',description:'Recupera memórias confirmadas e hipóteses candidatas do Agente Cliente neste escopo.',inputSchema:{type:'object',additionalProperties:false,required:['scopeType','scopeId'],properties:{tenantKey:{type:'string',maxLength:120},scopeType:{type:'string',maxLength:60},scopeId:{type:'string',maxLength:120},limit:{type:'integer',minimum:1,maximum:12}}}};}
function memoryWriteTool(){return{name:'registrar_aprendizado_candidato',description:'Registra uma hipótese de aprendizado; nunca a confirma automaticamente.',inputSchema:{type:'object',additionalProperties:false,required:['scopeType','scopeId','specialty','content','evidence','confidence'],properties:{tenantKey:{type:'string',maxLength:120},scopeType:{type:'string',maxLength:60},scopeId:{type:'string',maxLength:120},specialty:{type:'string',maxLength:120},content:{type:'string',maxLength:4000},evidence:{type:'string',maxLength:4000},sourceReference:{type:'string',maxLength:700},confidence:{type:'number',minimum:0,maximum:1}}}};}
async function callMemory(method,args){const root='/api/internal/agent-memory/v1/agents/customer-agent';const path=method==='GET'?`${root}?${new URLSearchParams({...(args.tenantKey?{tenantKey:args.tenantKey}:{}),scopeType:args.scopeType,scopeId:args.scopeId,limit:String(args.limit??8)})}`:root;const body=method==='POST'?JSON.stringify({...args,sourceExecutionId:String(evaluationId)}):undefined;const response=await fetch(base+path,{method,headers:{Accept:'application/json','Content-Type':'application/json'},body,signal:AbortSignal.timeout(30000)});process.stderr.write(JSON.stringify({tool:method==='GET'?'recuperar_memoria_especializada':'registrar_aprendizado_candidato',evaluationId,path,status:response.status,at:new Date().toISOString()})+'\n');if(!response.ok)throw new Error(`Backend respondeu HTTP ${response.status}`);return{content:[{type:'text',text:await response.text()}]};}
function required(name){const value=process.env[name];if(!value)throw new Error(`Variável obrigatória ausente: ${name}`);return value;} function send(value){process.stdout.write(JSON.stringify(value)+'\n');}
