name: Success Worker CI

on:
  push:
    paths:
      - 'success-product-worker/**'
  pull_request:
    paths:
      - 'success-product-worker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
    defaults:
      run:
        working-directory: success-product-worker
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: Build and test
        run: mvn -B -s settings.xml package
